name: Node CI

on:
  push:
    branches:
    - develop
    - master
  pull_request:
    branches:
    - '**'

jobs:    
  release:
    name: Release
    runs-on: ubuntu-latest
    
    steps:
      
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Setup
      uses: actions/setup-node@v4
      with:
        node-version: 20.8.1
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint
      run: npm run lint
    
    - name: Test
      run: npm run test

    - name: i18n Extract
      run: npm run i18n_extract
    
    - name: Build
      run: npm run build
    
    - name: Coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
